version: '3'
services:
  db:
    image: mysql
    ports:
      - 3306:3306
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password